### ISSUE TITLE
Range Indicators for Spells

### ISSUE THREAD

**Issue by nfet** [kapresoft/wow-addon-actionbar-plus#11]
## As a player, I would like to have an indicator on the action button, so that I know that the action target is in-range and castable.

> Note: This is very similar to the standard blizzard action button functionality where a "red text" in the action button number is rendered if the target is not in range.

**Comment by kapresoft** [comment]
Fixed in [1.0.0.29](https://www.curseforge.com/wow/addons/actionbarplus/files/3982207)
