### ISSUE TITLE
Per Character Macro Rename Doesn't work

### ISSUE THREAD

**Issue by nfet** [kapresoft/wow-addon-actionbar-plus#14]
## Repro Steps
1. Drag a Per Character Macro to an ActionbarPlus action slot
2. Open Macro UI and rename a macro such that it triggers and index change.
   > With more than one macro in your Per Character Macro, rename a macro so that the order of the index of the macro is changed, i.e. imacro is in slot 5 and named "Attack", and renaming it to "#Attack" changes it to slot/index 1.
3. Hover on the ActionbarPlus action slot where the macro was assigned. Bug: Still shows the old name
4. Click on the ActionbarPlus action slot. Bug: Nothing happens

**Comment by kapresoft** [comment]
Fixed in [1.0.0.20](https://www.curseforge.com/wow/addons/actionbarplus/files/3831286)
