### ISSUE TITLE
`'ActionbarPlus' tried to call the protected function 'ActionbarPlusF1:Show()'`

### ISSUE THREAD

**Issue by tflo** [kapresoft/wow-addon-actionbar-plus#260]
Getting this error (or slight variants) repeatedly, but not regularly:

```text
3x [ADDON_ACTION_BLOCKED] AddOn 'ActionbarPlus' tried to call the protected function 'ActionbarPlusF1:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `Show'
[string "@ActionbarPlus/Core/Lib/Widget/Buttons/ButtonFrameFactory.lua"]:483: in function `ShowGroup'
[string "@ActionbarPlus/Core/Lib/Widget/Buttons/ButtonFrameFactory.lua"]:227: in function <...rPlus/Core/Lib/Widget/Buttons/ButtonFrameFactory.lua:227>
```

This doesn't seem to be taint stuff (I have no problems casting spells via keys or buttons after this error, nor do I get the taint pop-up box), and it doesn't seem to have any consequences at all, but I think you could be interested in that.

I haven't yet tried to verify if the error still occurs without any non-Blizz addons loaded, but I could do if you think it would help.

---

PS: None of my ABP buttons has F1 assigned to it. Actually I do not have any key binds at all to ABP buttons.

**Comment by nfet** [comment]
Do you recall if the character was in combat when the error occurred? I have never seen this before.  I will see if I can repro. 

It looks like `<Frame|ScriptRegion:Show()>` is restricted can't be called during combat.

This function is [restricted](https://wowpedia.fandom.com/wiki/Category:API_functions/restricted).
secureframecombat - This cannot be called on secure frames during combat; see [SecureStateDriver](https://wowpedia.fandom.com/wiki/SecureStateDriver).

https://wowpedia.fandom.com/wiki/API_ScriptRegion_Show
<img width="589" alt="image" src="https://user-images.githubusercontent.com/1599306/232351165-203318ef-344f-43ba-8709-c28c68fd4488.png">


Cheers,

**Comment by nfet** [comment]
>PS: None of my ABP buttons has F1 assigned to it. Actually I do not have any key binds at all to ABP buttons.

BTW, `ActionbarPlusF1` is just the parent frame for the action bar slots, i.e. `/dump ActionbarPlusF1` should display the object properties, where 1 represents the action bar number, i.e. ActionbarPlusF<frame-index>

**Comment by tflo** [comment]
> Do you recall if the character was in combat when the error occurred?

Nah, not sure. Will pay more attention next time. (Since the error seems to have no effects, it was low priority to me)

> I have never seen this before.

I've first seen this shortly after I reinstalled ABP a couple of days ago, and from then on more or less regularly. If you don't see it at all, then probably there is indeed some interference with some other addon in play.

In regards to action-bar-related addons, I'm using none (not Dominos and not Bartender). Otherwise button-related addons I'm using are M6, OPie, Select, Macro Toolkit, Molinari. Frame-related: BlizzMove and MoveIt.

**Comment by tflo** [comment]
OK, just had it again, in combat. Though it can't be excluded that it happend shortly before or shortly after combat. But the current toon is farming souls with the Soul Inhaler, i.e. I'm logging in every 20 minutes just to kill an Elemental and not doing anything else, so it is at least likely that it was during combat.

```
1x [ADDON_ACTION_BLOCKED] AddOn 'ActionbarPlus' tried to call the protected function 'ActionbarPlusF1:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `Show'
[string "@ActionbarPlus/Core/Lib/Widget/Buttons/ButtonFrameFactory.lua"]:483: in function `ShowGroup'
[string "@ActionbarPlus/Core/Lib/Widget/Buttons/ButtonFrameFactory.lua"]:227: in function <...rPlus/Core/Lib/Widget/Buttons/ButtonFrameFactory.lua:227>
```

**Comment by nfet** [comment]
Cool. I can make it a safecall and log the errors with a higher log level. Thanks!

**Comment by tflo** [comment]
By the way, the error is still there – or there again, because I was under the impression that it had been fixed at some point. 
But it's possible that it was only fixed in one of the builds I downloaded from the repo, IDK (I didn't play for some time). 

I'm currently in sync with your CF releases again, which have seen several updates since then (but mostly localization-related, it seems).

This is not meant to pressure you, just mentioning it in case there really is a regression.

**Comment by nfet** [comment]
I have not been able to repro this. Which wow version are you playing?

**Comment by tflo** [comment]
I've added an edit to my above post, maybe it was at the same time you replied, in case you don't see it please reload the page.

My WoW version is: `10.0.7 49343 Apr 26 2023 100007`

**Comment by nfet** [comment]
Hi There,

I'm able to repro now. I actually had to install Bug Grabber to get it to display.  Blizz actually just suppresses it with a message `Interface action failed because of an AddOn` msg.  I'll get this fixed in the next few days. 

![image](https://user-images.githubusercontent.com/1599306/235237104-ffe7e493-1ee8-450c-bc73-171baae98185.png)

**Comment by tflo** [comment]
Yes, BugBrabber/BugSack is quite essential.

Maybe it is suppressed by default (by the Blizz module) in this case because it comes without consequences? Strange though, it should show up anyway.

**Comment by nfet** [comment]
I just released the fix.  Thanks for helping make this add-on better.  Let me know if you see anything else.

- [Release 2023.4.11](../releases)
- [CurseForge](https://legacy.curseforge.com/wow/addons/actionbarplus/files/4511301)

**Comment by tflo** [comment]
>Thanks for helping make this add-on better. 

You are welcome. Since I'm using this addon, and the selfish I am, it is a no-brainer to spit out any info that could contribute to make it even better!

**Comment by tflo** [comment]
> Let me know if you see anything else.

Correct display of labels of M6 macros are currently my main (and only) issue. But that's another thread.
