### ISSUE TITLE
M6: Use M6 Macro Name instead of the Blizzard Macro Name

### ISSUE THREAD

**Issue by nfet** [kapresoft/wow-addon-actionbar-plus#264]
## Bug

With the new ABP version, the example from the [OP](https://github.com/kapresoft/wow-addon-actionbar-plus/issues/256#issue-1669388812) now shows the correct icon, but the labels are still missing:

<img width="611" alt="WoWScrnShot_041723_181621" src="https://user-images.githubusercontent.com/1410282/232548942-852198a2-f3f8-4b78-b0bf-2ee47d89ca41.png">

Also the tooltip does not show the label (it just shows the macro text from the stub, e.g. `_M6+s07`)

The label is constructed with `#label <labeltext>` in M6. See the screenshot in the first spoiler of the OP.

The labels are not _super-hyper_-important, but, as you can see in the example, they can be pretty helpful to identify the content of the macros. (In this case they set the posting quantity in Auctionator to a predefined number.)

_Originally posted by @tflo in https://github.com/kapresoft/wow-addon-actionbar-plus/issues/256#issuecomment-1511712331_

**Comment by nfet** [comment]
## Here's a preview of upcoming label and tooltip names support for M6 Spell type macros

### M6 Macro Contents

```
/castsequence [@player]  reset=10 Mage Armor, Arcane Intellect
```

### Initial State
> Initial Icon is `Mage Armor`

![image](https://user-images.githubusercontent.com/1599306/233161382-ec9c65c8-bf0b-4bd7-8f4a-b8a334f81f50.png)

### First Click
> After first click, the icon is updated to `Arcane Intellect`

![image](https://user-images.githubusercontent.com/1599306/233161572-592dd4e8-3467-4a10-b857-571ac3639a4f.png)

### After 10 Seconds (reset=10)
- The icon resets back to Mage Armor

**Comment by tflo** [comment]
Thanks for the preview, that's great!

For the sake of completeness, does the icon also work with [`/qsequence`](https://www.townlong-yak.com/addons/m6/macros#qsequence)?

```
/qsequence [@player] Mage Armor, Arcane Intellect
```

And with the states via flags, e.g. my Rogue healing macro:

```
#label cv/hp
/cast [btn:1,combat,flag:potion] Refreshing Healing Potion; [btn:1] Crimson Vial
/cycleflag [combat] potion 
/setflag [nocombat] potion=
```

Or the [`[visual]`](https://www.townlong-yak.com/addons/m6/conditionals) conditional?

**Comment by nfet** [comment]
I have read through the M6 addon code to understand most of what it's doing.  Just a heads up that I am planning to revert all the M6 code within ActionbarPlus and spin off a new addon called ActionbarPlus-M6.  I need to come up with a cleaner and more modularized solution.  Sorry for the inconvenience but I will try to push on the implementation as fast as possible. 

Cheers,

**Comment by tflo** [comment]
>  to understand most of what it's doing

Yeah, I don't understand everything it does yet either ;)

> I am planning to revert all the M6 code within ActionbarPlus and spin off a new addon called ActionbarPlus-M6

That's interesting. I feel a bit bad now that I have triggered all this work (considering that probably not too many people use M6 and ABP at the same time).
The ActionbarPlus-M6 will also work with "normal" macros, right? Or will it be M6 exclusive?

>  Sorry for the inconvenience but I will try to push on the implementation as fast as possible

No hurry! M6 macros work on ABP and the icons are there now, that's the most important thing. 

In the previous post where I asked about icon compatibility with /qsequence, flags and [visual], I said "for the sake of completeness" because I don't currently use macros with those features on any ABP bar, so no problem for me at all!

**Comment by nfet** [comment]
>That's interesting. I feel a bit bad now that I have triggered all this work (considering that probably not too many people use M6 and ABP at the same time).
The ActionbarPlus-M6 will also work with "normal" macros, right? Or will it be M6 exclusive?

ActionbarPlus will work with normal blizz macros.  I have a version of code that supports M6 now in a branch.  The more I was coding this it just made sense to push this code to another addon.  This is actually interesting work and I'm understating this.  M6 actually integrates/hooks directly to the blizzard actionbar functions and this is the reason that it doesn't function correctly in ABP.

ActionbarPlus 
- Will work as is, i.e. functions the same way as standard blizzard actionbars
- When a user drags and drop a M6 macro, the user will be prompted to install ActionbarPlus-M6.
- I plan to leave the current M6 integration alone and roll out the new ABP-M6 in a graceful manner
ActionbarPlus-M6 (Lightweight)
- Installing this will make ABP work with M6 macros ( supports all macros, spell and item cooldowns, item counts, mods [alt, ctrl, shift, etc] and usability states ).  This first release will have the MVP features at least.

The above structure works well as far as usability, stability and code maintenance.  Even if we might think not too many people use M6 with ActionbarPlus, I still feel like M6 deserves a clean integration in ABP.

> In the previous post where I asked about icon compatibility with /qsequence, flags and [visual], I said "for the sake of completeness" because I don't currently use macros with those features on any ABP bar, so no problem for me at all!

Don't feel bad, I just forgot to reply to let you know that, the way I've integrated ABP currently, all of the qsequence, flags, visual, etc works.  I'm actually learning a lot.  Also, I am planning to create a new addon called `ActionbarPlus-Masq` to integrate Masq addon as well (a user request)

The branch is here (and it's stable), but I wouldn't rely on this branch to remain the same (I'm always force pushing)
- https://github.com/kapresoft/wow-addon-actionbar-plus/compare/main...m6-name

**Comment by nfet** [comment]
> Correct display of labels of M6 macros are currently my main (and only) issue. But that's another thread. 🤪

I'm made significant progress on ActionbarPlus-M6.  I developed it under WOTLK. I just need wrap things up and make sure it works in retail.  I just need to finalize/wrap up the `m6-main-addon` branch and should be good to go for the first release.

- Full m6 macro support with cooldowns, usability, and item count
- No item charge support yet, i.e. mana gem charge count.

https://github.com/kapresoft/wow-ActionbarPlus-M6/releases/tag/0.0.1 (Alpha)
  - Curseforge project is pending
  - Wow Interface is good to go for [ActionbarPlus-M6](https://www.wowinterface.com/downloads/author-354119.html)
https://github.com/kapresoft/wow-addon-actionbar-plus/compare/m6-main-addon
  - verify in wow retail

**Comment by tflo** [comment]
Tranquilo. Just wanted to get rid of the Red bag (BugSack).

The rest is already fine for me, I have an icon for my M6 macros, so that i can at least identify them. The gory stuff, like labels and such later…

Many thanks for your work and for your awareness and responsiveness!

– Tom

**Comment by nfet** [comment]
For the initial implementation, this is what I have. It can be improved in the future.

### Tootlip Info: Without `#label <label>`
> Use the M6 Macro Name

![image](https://user-images.githubusercontent.com/1599306/235278306-c50b061e-19fd-4990-8cc4-4ae49af67e8c.png)

### Tooltip Info: If a `#label <label>` is defined
> Use the Label name

![image](https://user-images.githubusercontent.com/1599306/235278257-db2d4aa5-fc2d-4be1-9efc-a9298397b843.png)

The M6-Name will be placed in (#2) and Label will be used in (#3), The (#1) is the actual macro name.

**Comment by nfet** [comment]
Here's another. Holding down SHIFT while mouseover will show macro details.

![Screenshot 2023-04-29 at 2 12 36 PM](https://user-images.githubusercontent.com/1599306/235324437-542a7bc4-c774-45aa-ab8f-4495d8ecaf51.png)

**Comment by tflo** [comment]
Oh, this is nice! 🙂

**Comment by nfet** [comment]
Hi There, 

ActionbarPlus-M6 1.0.0 is out :-) Party! 🥳.  You have to get the latest ActionbarPlus 2023.4.12 as well.  I have tested in Retail, Classic, and Classic Era.  Good Luck & have fun.

Switching sepcs is a bit hoaky because the M6 profiles re-uses the wow macros and ABP currently does not support profile-per-specialization settings.

The add-on has dependency on both ABP and M6. 

https://legacy.curseforge.com/wow/addons/actionbarplus-m6/files
https://legacy.curseforge.com/wow/addons/actionbarplus/files

Cheers,

**Comment by tflo** [comment]
I don't want to be the party killer — and I'm sure it's a small thing, but I get this:

```text
44x ...rfaceActionbarPlus-M6/Core/Lib/M6Support.lua:285: attempt to index field '?' (a nil value)
[string "@ActionbarPlus-M6/Core/Lib/M6Support.lua"]:285: in function `profile'
[string "@ActionbarPlus-M6/Core/Lib/M6Support.lua"]:467: in function `InitializeHooks'
[string "@ActionbarPlus-M6/Core/Lib/M6Support.lua"]:505: in function <...rfaceActionbarPlus-M6/Core/Lib/M6Support.lua:499>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:59: in function `SendMessage'
[string "@ActionbarPlus/Core/Lib/Widget/ActionbarPlusEventMixin.lua"]:301: in function <...nbarPlus/Core/Lib/Widget/ActionbarPlusEventMixin.lua:301>
```

Clicks seem to work fine though.
The error then gets thrown again with every mouseover over an M6 macro button on ABP.

This is with both ABPs loaded, and happens also with (almost) no other addons:

<img width="950" alt="WoWScrnShot_050123_004719" src="https://user-images.githubusercontent.com/1410282/235379685-27976b2f-be58-49bc-97f5-03715c2f5ba0.png">

After a reload, the M6 macros I've put on a bar before, turn green. Until I move them, then the icon comes back.

**Comment by nfet** [comment]
Taking a look now....

**Comment by nfet** [comment]
I knew it. It was too early to celebrate :-).

I can't repro on my side, but this seems like not being able to access the M6DB.  The add-on needs to access action the M6 character profile in able to get information about each m6 action.

What does this give you on the console?
```
/dump M6DB
```

Line 285 calls `db()` which returns M6DB.
https://github.com/kapresoft/wow-ActionbarPlus-M6/blob/476318c622ae9be2e9d0f837638647335cd7acd7/Core/Lib/M6Support.lua#L280-L285

![Screenshot 2023-04-30 at 4 59 32 PM](https://user-images.githubusercontent.com/1599306/235382187-a9370047-20af-4296-acd0-9d32d8e2ec3a.png)

Also, could I get you to try it on a character that has not used the M6 add-on before?

I made a small patch [1.0.1](https://legacy.curseforge.com/wow/addons/actionbarplus-m6/files/4514686) to log on the console if M6DB is not accessible.

**Comment by nfet** [comment]
...and I'm gonna keep poking around. I'm sure I can find the issue soon enough.

**Comment by tflo** [comment]
> What does this give you on the console?
> 
> ```
> /dump M6DB
> ```

Well, it returns the whole M6 database.

**Comment by tflo** [comment]
Loaded your 1.0.1 now. It returns this line after reload:

```
{{ActionbarPlus-M6}}: 1.0.1 Initialized
```

The error seems to be the same, with shifted line numbers:

```
1x ...rfaceActionbarPlus-M6/Core/Lib/M6Support.lua:291: attempt to index field '?' (a nil value)
[string "@ActionbarPlus-M6/Core/Lib/M6Support.lua"]:291: in function `profile'
[string "@ActionbarPlus-M6/Core/Lib/M6Support.lua"]:473: in function `InitializeHooks'
[string "@ActionbarPlus-M6/Core/Lib/M6Support.lua"]:511: in function <...rfaceActionbarPlus-M6/Core/Lib/M6Support.lua:505>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:59: in function `SendMessage'
[string "@ActionbarPlus/Core/Lib/Widget/ActionbarPlusEventMixin.lua"]:301: in function <...nbarPlus/Core/Lib/Widget/ActionbarPlusEventMixin.lua:301>
```

**Comment by tflo** [comment]
The problem could be your `GetNormalizedRealmName()` in line 290.

The normalized name of my realm is `AzjolNerub`. But in the M6 profile it's the non-normalized name (`Azjol-Nerub`).

**Comment by tflo** [comment]
Yeah, no errors with:

```lua
        local realm, name = GetRealmName(), UnitName("player")
```

Line 290, M6Support.lua

**Comment by tflo** [comment]
OK, I think you can party now 😀

Just a minor cosmetic issue: There are double colons (`::`) in the tooltip:

<img width="380" alt="WoWScrnShot_050123_024533" src="https://user-images.githubusercontent.com/1410282/235384400-e81a62d9-7231-459a-a61e-6ef36a6f615f.png">

**Comment by tflo** [comment]
And, damn, the shift-tooltip with the macro text is really useful!

What you have done has exceeded all my expectations!

**Comment by nfet** [comment]
> Yeah, no errors with:
> 
> ```lua
>         local realm, name = GetRealmName(), UnitName("player")
> ```
> 
> Line 290, M6Support.lua

Wow. Good catch. 👍  I don't know why I picked `GetNormalizedRealmName()` when I totally saw that m6 Core.lua uses GeatRealmName().  Will put out a fix shortly.

**Comment by nfet** [comment]
>And, damn, the shift-tooltip with the macro text is really useful!
>What you have done has exceeded all my expectations! 
Nice! This is great to hear!  I wish that the "spellID" values were converted to real spell names though. Well see what the future holds.

**Comment by tflo** [comment]
OK, but now the real problem is – quoting [you](https://github.com/kapresoft/wow-addon-actionbar-plus/issues/264#issuecomment-1529153267) – :

> Switching specs is a bit hoaky because the M6 profiles re-uses the wow macros and ABP currently does not support profile-per-specialization settings.

Actually this means that any M6 macro I put on an ABP bar will change to something else (or empty) when I switch chars.

I didn't notice that until now, because the only toons where I fully switched from a Blizz action bar full with M6 macros to an ABP bar with the same macros, were my AH toons. And there, the macros remained "stable" between the toons.

And I think I know now why this is…

I deactivated the old Blizz action bars with the M6 macros, but I did not delete the macros from them. So, M6 reliably recreates the macros on both AH toons because they are _persistently_ still present on the (hidden) Blizz action bars.

And I guess in the moment when I remove the macros from the Blizz bars, they will get completely messed up on the ABP bar, depending on which macros M6 actually puts into the macro slots at login.

**Comment by tflo** [comment]
Well, actually they don't even work on AH toon <span>#</span>2. The labels are the same, but hovering over the icons produces this:

```text
{{ActionbarPlus-M6::M6Support}}: Failed to show tooltip for unknown actionID, slotID=s0d macro=_M6+s0d
{{ActionbarPlus-M6::M6Support}}: Failed to show tooltip for unknown actionID, slotID=s0e macro=_M6+s0e
{{ActionbarPlus-M6::M6Support}}: Failed to show tooltip for unknown actionID, slotID=s12 macro=_M6+s12
{{ActionbarPlus-M6::M6Support}}: Failed to show tooltip for unknown actionID, slotID=s11 macro=_M6+s11
{{ActionbarPlus-M6::M6Support}}: Failed to show tooltip for unknown actionID, slotID=s10 macro=_M6+s10
{{ActionbarPlus-M6::M6Support}}: Failed to show tooltip for unknown actionID, slotID=s0f macro=_M6+s0f
{{ActionbarPlus-M6::M6Support}}: Failed to show tooltip for unknown actionID, slotID=s10 macro=_M6+s10
{{ActionbarPlus-M6::M6Support}}: Failed to show tooltip for unknown actionID, slotID=s11 macro=_M6+s11
```

… and they actually don't work.

I thought they worked until recently, but I'm not sure now because it's been a while since I've been on that toon.

**Comment by nfet** [comment]
> OK, I think you can party now 😀
> 
> Just a minor cosmetic issue: There are double colons (`::`) in the tooltip:
> 
> <img alt="WoWScrnShot_050123_024533" width="380" src="https://user-images.githubusercontent.com/1410282/235384400-e81a62d9-7231-459a-a61e-6ef36a6f615f.png">

The `Drain Soul` :: `<name or label>` is intentional.
For `M6 Macro ::` and `Name ::` I'll have a fix shortly

**Comment by nfet** [comment]
My workaround currently is to create a profile for each spec

> Well, actually they don't even work on AH toon #2. The icons are the same, but hovering over the buttons produces this:
> 
> ```
> {{ActionbarPlus-M6::M6Support}}: Failed to show tooltip for unknown actionID, slotID=s0d macro=_M6+s0d
> {{ActionbarPlus-M6::M6Support}}: Failed to show tooltip for unknown actionID, slotID=s0e macro=_M6+s0e
> {{ActionbarPlus-M6::M6Support}}: Failed to show tooltip for unknown actionID, slotID=s12 macro=_M6+s12
> {{ActionbarPlus-M6::M6Support}}: Failed to show tooltip for unknown actionID, slotID=s11 macro=_M6+s11
> {{ActionbarPlus-M6::M6Support}}: Failed to show tooltip for unknown actionID, slotID=s10 macro=_M6+s10
> {{ActionbarPlus-M6::M6Support}}: Failed to show tooltip for unknown actionID, slotID=s0f macro=_M6+s0f
> {{ActionbarPlus-M6::M6Support}}: Failed to show tooltip for unknown actionID, slotID=s10 macro=_M6+s10
> {{ActionbarPlus-M6::M6Support}}: Failed to show tooltip for unknown actionID, slotID=s11 macro=_M6+s11
> ```
> 
> … and they actually don't work.
> 
> I thought they worked until recently, but I'm not sure now because it's been a while since I've been on that toon.

My workaround (without M6) currently is to have a profile for each spec in the Profiles menu.  I do have to manually switch ABP profile after switch spec.  It's a bit manual but the Ace3 config support is fairly easy to use, i.e. copy current profile into a new one...just mentioning in case you have not used this before.

After setting up a profile for each spec, my steps are:
1) Switch Talent
2) `/abp conf`
3) In profiles menu, select the profile and reload (A bit manual at the moment)

I'm getting closer to formulating a solution for switching profiles.  The tracking issue is #167 "Dual Spec Support"

![image](https://user-images.githubusercontent.com/1599306/235395043-4e4d2735-cb84-4522-b4a1-d98da6ad91c2.png)

**Comment by tflo** [comment]
But keep in mind that the main advantage of ABP over the regular action bars is that you can have global bars, i.e. cross-char bars. (Well, at least for me this is the reason for using ABP.)

Having to recopy profiles for 20 toons every time I make a change would kind of defeat the purpose, right?

**Comment by nfet** [comment]
> 



> OK, but now the real problem is – quoting [you](https://github.com/kapresoft/wow-addon-actionbar-plus/issues/264#issuecomment-1529153267) – :
> 
> > Switching specs is a bit hoaky because the M6 profiles re-uses the wow macros and ABP currently does not support profile-per-specialization settings.
> 
> Actually this means that any M6 macro I put on an ABP bar will change to something else (or empty) when I switch chars.
> 
> I didn't notice that until now, because the only toons where I fully switched from a Blizz action bar full with M6 macros to an ABP bar with the same macros, were my AH toons. And there, the macros remained "stable" between the toons. (It's the bar [shown in the OP](https://github.com/kapresoft/wow-addon-actionbar-plus/issues/264#issue-1671926394).)
> 
> And I think I know now why this is…
> 
> I deactivated the old Blizz action bars with the M6 macros, but I did not delete the macros from them. So, M6 reliably recreates the macros on both AH toons because they are _persistently_ still present on the (hidden) Blizz action bars.
> 
> And I guess in the moment when I remove the macros from the Blizz bars, they will get completely messed up on the ABP bar, depending on which macros M6 actually puts into the macro slots at login.

m6 plays magic underneath those `_M6+<slotID>` macros, i.e. _M6+s01, _M6+s02, etc...

In one profile (same char different talent), s01 could be pointing to actionID #1.
When switching specs, now s01 could be pointing to actionID #2.  It's apparent in the SavedVariables/M6.lua file.  So the old action button no longer has the same information before it switched spec.

I believe having a different ABP profile should mitigate this issue but it's a temp fix.

**Comment by nfet** [comment]
> I believe having a different ABP profile should mitigate this issue but it's a temp fix.

Correction, having a different character profile per spec should mitigate this issue but it's a temp fix.

**Comment by nfet** [comment]
v. 2023.4.1 is out
https://legacy.curseforge.com/wow/addons/actionbarplus-m6/files/4514904

Cheers!

**Comment by nfet** [comment]
I tested in 'Azjol-Nerub' and 'Blood Furnace' to be sure.

**Comment by tflo** [comment]
> but it's a temp fix

Happy to hear that :-)

**Comment by nfet** [comment]
I just tried the profile-per-talent-spec setting and seems to work fine. 

Switch talent, then switch ABP profile.   For this character `Belat::BF:Disc` and `Belat::BF:Shadow`.  You would need to drag and drop the M6 macros to ABP for each spec profile switch though, i.e. the _M6+s01 macro in one spec may or may not be the same M6 action for another spec.

![image](https://user-images.githubusercontent.com/1599306/235402288-df08500a-c4de-4834-92d9-953758abe122.png)

**Comment by nfet** [comment]
> > but it's a temp fix
> 
> Happy to hear that :-)

...and thank you for the help!

**Comment by tflo** [comment]
> You would need to drag and drop the M6 macros to ABP for each spec profile switch though

Hm, probably this explains why my AH toon <span>#</span>2 has lost the correct macro attributions: Both AH toons share the same"AH" profile, but when I switch to one of the other, non-AH, toons (which all share the same "Default" profile) then the attributions get lost or mixed up?

But why are the macro attributions not lost then also on AH toon <span>#</span>1? (She has the macros also on hidden a Blizz action bar, but so does AH toon <span>#</span>2.)

And why do the icons remain intact on AH toon <span>#</span>2?

**Comment by nfet** [comment]
> And why do the icons remain intact on AH toon #2?

In ActionbarPlus? The ActionbarPlus-M6 addon records that last known icon, which may or may not be a bad idea (still unsure of this).  If it can't find the M6 Macro(Action), hence no icon, it uses the last known icon.  This might be the reason.  For the standard blizz action bar, It will be the green icon I think. 

-------
For the behavior of M6 in terms of profile data, here comes the long-winded answer...

Here's an example M6 with a blank profile for my Blood Furnace retail account with some M6-Macro (called Actions ).  The index of each actions are referred to in M6 code as Action Index or ID.

- https://gist.github.com/nfet/8b08edc5577261373e574353410bfebd#file-retail-m6-lua-L58-L60

By default, the actions are not active. In order for a macro to be active the player right-clicks on the M6 Macro(Action) and select 'Place on action bars'.
> I'm not sure if you're seeing the same experience, but I right-click and place on action bars and I still get the `?` icon.  I have to edit and save again to actually activate the icon.

In this example, I activated and dragged the `#PriestBuffSelf` M6 Macro to a stancard actionbar slot or ABP action slot.

After this action, I do a `/reload` (to force WOW to update profiles), then the character profile now looks like this.

```lua
["profiles"] = {
    ["Blood Furnace"] = {
        ["Belat"] = {
            {
                ["slots"] = {
                    ["s01"] = 7,
                },
                ["bind"] = {
                },
            }, -- [1]
        },
    },
},	
```

Action Index 7 is `#PriestBuffSelf` from this action array in my profile
- https://gist.github.com/nfet/8b08edc5577261373e574353410bfebd#file-retail-m6-lua-L51-L56

```lua
{
    "imptext", -- [1]
    "#label Buff me baby!\n/qsequence {{spell:21562}}, {{spell:2061}}", -- [2]
    ["group"] = 1,
    ["name"] = "#PriestBuffSelf",
}, -- [7]
```

I then activate and drag-and-drop another M6 Macro(Action) called `Hello` to an actionbar (standard or ABP); then do another `/reload`

The character profile now looks like this as expected:

```lua
["Belat"] = {
    {
        ["slots"] = {
            ["s01"] = 7,
            ["s02"] = 2,
        },
        ["bind"] = {
        },
    }, -- [1]
},
```

Action Index 2 is the `Hello` M6 Macro(Action) in my profile:
- https://gist.github.com/nfet/8b08edc5577261373e574353410bfebd#file-retail-m6-lua-L20-L26
```lua
{
    "imptext", -- [1]
    "#label Say Hello\n/run print('Hello')", -- [2]
    ["group"] = 3,
    ["name"] = "Hello",
    ["icon"] = 132093,
}, -- [2]
```

If I deactivate, the M6 Macro `Hello`, I added a hook in place to remove this action from ABP. In standard actionbar, the icon is updated to the `?` macro, which is just a plain macro with no assigned icon.

Another `/reload` will show that the `s02` mapping no longer exists in the character profile.

```lua
["Belat"] = {
    {
        ["slots"] = {
            ["s01"] = 7,
        },
        ["bind"] = {
        },
    }, -- [1]
},
```

The above behavior is fairly predictable.

For the purpose of this example, I will reactivate M6 Macro `Hello` again so that we are back to to slot entries.  After re-activating, the profile is now back to:

```lua
["Belat"] = {
    {
        ["slots"] = {
            ["s01"] = 7,
            ["s02"] = 2,
        },
        ["bind"] = {
        },
    }, -- [1]
},
```

## What happens when a character switches to a different spec?
After activating the Shadow spec (talent index 3), the behavior will be:
- all M6 Macros are deactivated by default on a new M6-profile.
- Blizzard removes the macro (probably because it uses a different profile for the action bar)
- The behavior now for ABP is it renders the Last Known icon, but points to the `_M6+s01` and `_M6+s02` shell macros, which renders no information since these are inactive M6 macros by default.  My thought is to remove these macros from ABP after a profile switch, for reasons which I will outline in a bit.  My future goal is to select a new ABP profile after a spec switch.

**Here's the behavior in M6.**

If I activate the M6 Hello macro first, this action will be assigned to slot `s01`.  If you recall on the previous profile that `s01` is assigned to `#PriestBuffSelf` macro (index:7).

So, after activating `Hello` macro and dragging and dropping to an ABP action slot, the character profile now looks like this (M6 creates a new profile for the spec, mapped by talent index 3) and a new slot `s01` is mapped to action index 2.  If you compare to the previous spec entry, `s01` maps to action index 7.

```lua
["profiles"] = {
    ["Blood Furnace"] = {
        ["Belat"] = {
            {
                ["slots"] = {
                    ["s01"] = 7,
                    ["s02"] = 2,
                },
                ["bind"] = {
                },
            }, -- [1]
            [3] = {
                ["slots"] = {
                    ["s01"] = 2,
                },
                ["bind"] = {
                },
            },
        },
    },
},
```

If the action slot is inactive, Actionbar-M6 is not able to pull information about that action and also clicking on it will not work (for both ABP and standard actionbar slot).

My thoughts are the better ABP user-experience might be after a profile switch is to
- switch to a new ABP profile (in the works) -- has to be done manually for now
- remove inactive M6 Macros from ABP

**Comment by nfet** [comment]
> But why are the macro attributions not lost then also on AH toon #1? (She has the macros also on a hidden Blizz action bar, but so does AH toon #2.)

If you activated and dragged-and-dropped the M6 Macros in the same order such that the slots map to the same action index, it is possible that the macros will continue to work on subsequent spec change.

**Comment by nfet** [comment]
One thing I did overlook is the `SavedVariablesPerCharacter` settings.  

**M6.toc:**
```
## SavedVariables: M6DB
## SavedVariablesPerCharacter: M6PC
```
Can you give this a try on the same character.
Console:
```
/dump M6PC
```

**Comment by nfet** [comment]
Oh never mind...I just got the same error on retail.

**Comment by nfet** [comment]
...hang tight while I figure things out. Looks like this will only affect tooltips.  M6 Macros still work in ABP. Let me see if I can get a quick fix today.

**Comment by tflo** [comment]
> Let me see if I can get a quick fix today 

No need to hurry, at least not because of me. In fact, with additional complications now showing up, I would even consider abandoning the whole experiment – unless the educational benefits are worth it.

You were smart enough to separate this thing from the main ABP project, so you could just drop it.

**Comment by nfet** [comment]
Oh don't worry. M6 codebase is going through some code cleanup. This is always the business with dependency. This will be fixed shortly. The "detailed" tooltip will no longer be available due to changes. The m6 macro details on hover is a nice-to-have feature but not needed.

**Comment by nfet** [comment]
ActionbarPlus-M6 2023.5.3 is out
- https://legacy.curseforge.com/wow/addons/actionbarplus-m6/files/4522509

**Comment by nfet** [comment]
That's unexpected.  It should only have missing tooltip non-spell/item type macros like emotes.  What is the content of this m6 macro?

Here's a buff macro for one of my tests

![image](https://user-images.githubusercontent.com/1599306/236510680-79ffddeb-20f1-4177-b43c-3bfb15d8e250.png)

**Comment by tflo** [comment]
> What is the content of this m6 macro?

It's still the same bar with Auctionator scripts from my [original post](https://github.com/kapresoft/wow-addon-actionbar-plus/issues/256#issue-1669388812). So, for example:

```
#icon 1505925
#label 192
/run AuctionatorSellingFrame.SaleItemFrame.Quantity:SetNumber(192)
```

BTW, the label text (on the button, not in the tooltip) is still (or again?) missing. Didn't we have the text in one of the previous versions?

**Comment by nfet** [comment]
OK, then that was the expected tooltip for now for non/spell/item types.
>/run AuctionatorSellingFrame.SaleItemFrame.Quantity:SetNumber(192)

For this one: I never added the macro name text (or label) in the original ABP or the ABP-M6 addon because it convolutes the button (just my preference and it doesn't mean it's right for other players).  

I can provide an option if this is needed.   I can see how you might find this useful.  There's not a lot of real estate in that button for texts anyways.  Let me know.

> BTW, the label text (on the button, not in the tooltip) is still (or again?) missing. Didn't we have the text in one of the previous versions?

**Comment by tflo** [comment]
> For this one: I never added the macro name text (or label) in the original ABP or the ABP-M6 addon

OK, thanks. I am old and memory doesn't get better ;) (Actually, it was never really good...)

> because it convolutes the button

Labels are usually short. That's one of the good things about M6, that it doesn't abuse the macro name as labels, like Blizz does. This also means that there is no text on the button if there is no label declaration in the macro. So it's completely up to the user how "convoluted" the button will be.

>  I can see how you might find this useful.

Just have a look at [the screenshot](https://github.com/kapresoft/wow-addon-actionbar-plus/issues/264#issue-1671926394) in the topmost post here, and I think you'll also find labels on the button useful ;)

In this case I would even call them essential. As said, in other cases they are not super-hyper important, but still useful, yet alone because they tell me at a glance if the button is a macro or just an item/toy/spell.

Also in my more "normal" M6 macros, e.g. with spells and abilities, I use them to condense information into it. For example a label that contains "+t" means that the macro contains a `/use 13` or `/use 14` or both (Trinkets).
