### ISSUE TITLE
Feature: Add labels for M6 Macros

### ISSUE THREAD

**Issue by nfet** [kapresoft/wow-addon-actionbar-plus#277]
> For this one: I never added the macro name text (or label) in the original ABP or the ABP-M6 addon

OK, thanks. I am old and memory doesn't get better ;) (Actually, it was never really good...)

> because it convolutes the button

Labels are usually short. That's one of the good things about M6, that it doesn't abuse the macro name as labels, like Blizz does. This also means that there is no text on the button if there is no label declaration in the macro. So it's completely up to the user how "convoluted" the button will be.

>  I can see how you might find this useful.

Just have a look at [the screenshot](https://github.com/kapresoft/wow-addon-actionbar-plus/issues/264#issue-1671926394) in the topmost post here, and I think you'll also find labels on the button useful ;)

In this case I would even call them essential. As said, in other cases they are not super-hyper important, but still useful, yet alone because they tell me at a glance if the button is a macro or just an item/toy/spell.

Also in my more "normal" M6 macros, e.g. with spells and abilities, I use them to condense information into it. For example a label that contains "+t" means that the macro contains a `/use 13` or `/use 14` or both (Trinkets).

_Originally posted by @tflo in https://github.com/kapresoft/wow-addon-actionbar-plus/issues/264#issuecomment-1536561693_

**Comment by tflo** [comment]
I think your solution is very good: Color and outline are perfect, positioning is also very good, maybe a tiny bit too far from the button border. (But definitely better than Blizz's positioning, which is so close to the border that it makes the label look like it touches the border, which looks wrong). Also great that it is right-aligned, not centered.
