### ISSUE TITLE
Cooldown Count for Macros + Suggestion

### ISSUE THREAD

**Issue by tybaulk** [kapresoft/wow-addon-actionbar-plus#28]
When adding a macro TRINKET spell to the bar it will not display the macro cooldown or tooltip. (tooltip will just say 'macro') Other spells seem to work except for trinkets. ie. Macroing trinkets together etc.

Suggestion: Is it possible to hide the extra bars? I noticed you have an option to do so while in a taxi. Would be very awesome to have the ability to hide the bars out of sight.

**Comment by tybaulk** [comment]
Seems slots 13 and 14 will display the cooldown if dragged from the character pane. However, when writing a macro such as:

#showtooltip
/use 13

This macro will not show the cooldown or tooltip.

**Comment by kapresoft** [comment]
Great Suggestions.  I may never have tested a macro with a trinket before :-). 

For hiding bars you don't need, does the "Enable" do what you want it to do on each of the action bar settings?
For example `Settings / Action Bar #3 / "Enable" checkbox.`

**Comment by tybaulk** [comment]
Wow, I completely overlooked that! Thank you!

**Comment by nfet** [comment]
Fixed in v[1.0.0.26](https://www.curseforge.com/wow/addons/actionbarplus/files/3950548)
PR #32
