### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by tybaulk** [kapresoft/wow-addon-actionbar-plus#29]
![image_2022-08-24_013126364](https://user-images.githubusercontent.com/111405787/186336794-1bc58cc5-0722-46a4-b030-79f0f5e759f4.png)

Not sure how to reproduce this. I think it may have something to do with having the macro/trinket in the slots. This tends to happen when I try moving the bar with the macro trinkets on it.

**Comment by tybaulk** [comment]
I've managed to have 3 fatal errors. Usually when I click on the bar where I have only two slots that have those trinket macros.

**Comment by kapresoft** [comment]
My apologies for causing this. I'll try to repro and put a fix on this today.  What client are you using by the way? WOW Retail?

**Comment by nfet** [comment]
Oh Nevermind :-), I see '_classic_' on screenshot.

**Comment by nfet** [comment]
I've created a similar macro and have not been able to reproduce yet...will keep trying.

**Comment by nfet** [comment]
It took a while but as I was implementing the item cooldown on macros, i was dragging back and forth an action button and finally got this:

![image](https://user-images.githubusercontent.com/1599306/186491725-f34402a5-37e4-4d2f-bf86-af24dcfb2d2a.png)

**Comment by tybaulk** [comment]
Yeah that's it. I was messing around with it this morning and when I was clicking on and moving spells around on the macro frame and addon frame this error occurred.

**Comment by nfet** [comment]
If I continuously drag-and-drop two items, it crashes on 21st drag-and-drop. *sigh*.  Still figuring it out...

**Comment by nfet** [comment]
Fixed in v[1.0.0.26](https://www.curseforge.com/wow/addons/actionbarplus/files/3950548)
