### ISSUE TITLE
CPU usage too high

### ISSUE THREAD

**Issue by tflo** [kapresoft/wow-addon-actionbar-plus#295]
You [said](https://github.com/kapresoft/wow-addon-actionbar-plus/issues/256#issuecomment-1528183906):

> For performance for ABP, I need to run through and optimize some things. It has a high mem and high CPU reported by the "Addon Usage" addon when my character is in a big city. ABP goes garbage collection just fine though.

…and I [said](https://github.com/kapresoft/wow-addon-actionbar-plus/issues/256#issuecomment-1528440653):

> The first time I used your addon (a few months ago) I was also shocked by this. But then I learned that addons that are first in the alphabet tend to get blamed for memory and CPU usage of the AceLibs they contain, which should actually be distributed to all addons.
>
>In case you haven't, download and install the Ace Library separately and activate it in your addon manager. This should save some addons from being falsely accused, ABP being one of them:
>
>[…]
>
>The samples are a bit bad, because they were taken without much action, spellcasting, moving etc. But the general picture is OK. ABP goes a bit higher when really doing some fighting or such, but not that much.

Unfortunately it seems you were right and I was wrong, especially since one of your recent updates.

After installing [2023.6.1](https://www.curseforge.com/wow/addons/actionbarplus/files/4569574), it happened that I was in a raid group for the Researchers Under Fire event, and I got near-freezes, i.e FPS at 1 or below during combat. The FPS returned to normal immediately after combat.

I then repeated the event on another toon and with CPU profiling enabled, got similar FPS issues, and the CPU report is this:

<img width="484" alt="ABP CPU-pty-fs8" src="https://github.com/kapresoft/wow-addon-actionbar-plus/assets/1410282/4f72d1f7-d490-4cf4-baeb-af857d56fc80">

Of course, I cannot say with certainty that ABP is the responsible for the near-freezes, but this is completely unexpected and I have never seen it like this before. Normally, with a lot of combat, Hekili is the leader with about 40% CPU (it does a lot of calculations during combat, so I would consider this normal), followed at about 5%–15% by WeakAuras, TSM (WTF is it doing in combat?!!), OPie, M6, ….
ABP used to be in the 5%–15% group or below that group.

I then rolled back to the ABP version before 2023.6.1, repeated the thing, and ABP was not that high as before but still higher than what I would consider appropriate. I don’t have a screenshot but it was the leader of the 5%–15% group or above.

So it seems that with or without version 2023.6.1, but especially with version 2023.6.1, ABP’s CPU usage – during combat –  is indeed far too high. Even more so when you consider that I have no combat-related spells on an ABP bar.  This is the full screenshot from before, in the raid group with the ABP bars highlighted:

![ABP CPU total-fs8](https://github.com/kapresoft/wow-addon-actionbar-plus/assets/1410282/aef0af32-1bea-4968-ad54-92426284f157)

Only toys and items at that point.

After that, I went back to using [Button Forge](https://www.curseforge.com/wow/addons/button-forge) in place of ABP, and this thing has absolutely low CPU usage. Perhaps you can get an idea of what makes the difference by looking at their code. (I haven't done this, so this is merely hypothetical).

– Tom

**Comment by nfet** [comment]
To get a more accurate CPU Usage, Ace3 needs to be excluded in ABP (with Lib Ace3 addon installed) in _ExtLib.xml.

https://github.com/kapresoft/wow-addon-actionbar-plus/blob/e107ad9c6da2e115450985d422866f243dfc8886/Core/_ExtLib.xml#L7C1-L8

![Screenshot 2023-06-11 at 5 42 47 PM](https://github.com/kapresoft/wow-addon-actionbar-plus/assets/1599306/a8085a3e-3009-487a-98be-8e62d6647fc5)

**Comment by nfet** [comment]
I'm getting an idle CPU now of about 1.1+.   I will run this through a 5-man then see if there are any issues.

![Screenshot 2023-06-11 at 6 03 05 PM](https://github.com/kapresoft/wow-addon-actionbar-plus/assets/1599306/aefe5851-7252-498e-adc8-c363429b3634)

**Comment by nfet** [comment]
Hi @tflo,

Thank you for bringing up the CPU usage issue. I wanted to let you know that, at the moment, it's best to avoid using ABP/ABP-M6 for quite a while. I'm currently working on some significant improvements, but these changes may or may not meet the expectations of power users like yourself.

Cheers,
- Tony

**Comment by tflo** [comment]
> at the moment, it's best to avoid using ABP/ABP-M6 for quite a while.

Yeah, I came more or less to the same conclusion, hence my "Back to Button Forge" ;)

But thanks for the honest statement and confirmation.

**Comment by nfet** [comment]
Hi Tom,
That way I've approach the creation of ABP is mediocre at best and this is probably why perf issues are showing.  I've been so busy with other stuff that I am contemplating doing a stop dev on ABP.

**Comment by nfet** [comment]
FYI: Reverted to 2023.5.6 (Now labeled as 2023.6.10)

**Comment by tflo** [comment]
> Hi Tom,
That way I've approach the creation of ABP is mediocre at best and this is probably why perf issues are showing.  I've been so busy with other stuff that I am contemplating doing a stop dev on ABP.

Sorry to hear that, or maybe it's good, if the "other stuff" is important. In any case, ABP will remain on my "stay tuned for updates' list. Thanks again!
