### ISSUE TITLE
Latency on item move into bag with lastest update.

### ISSUE THREAD

**Issue by A7Capone** [kapresoft/wow-addon-actionbar-plus#298]
**Describe the bug**

When I move items in bag or action bars, there is a slight latency when clicking on the item.
The Latency is not present when I select a spell and move it. It seems to be items only.

 I disabled all addons and enabled em one by one to see which one was causing this. 

Issue come from lastest 6.3 update
if I rollback to the previous version  6.1 there is no latency at all.

**To Reproduce**

1. Open your bag
2. Click on any items into it
3. There is the little latency

**Expected behavior**
Instant click item like usual

**Operating System**
- OS: Windows 11 Pro - 22H2 build 22624.1755
- Version Retail

Thank you

**Comment by nfet** [comment]
Thanks. Will look into this now.

**Comment by nfet** [comment]
Hi @A7Capone , the fix is in [2023.6.4](https://legacy.curseforge.com/wow/addons/actionbarplus/files/4583004).

**Comment by A7Capone** [comment]
Thanks a lot !! Good work on the addon, I really appreciate it!!
