### ISSUE TITLE
[Enhancement] Hide tooltip

### ISSUE THREAD

**Issue by Evolvee** [kapresoft/wow-addon-actionbar-plus#30]
Hi,
I am currently using your addon instead of "ButtonForge" that is causing issues in WOTLK, however there is one thing I would appreciate if you could implement: hiding tooltips

basically I dont want to see this when I mouse-over the button:
![image](https://user-images.githubusercontent.com/1942409/186416555-2d6c3292-6ef5-40d4-9b28-de4be369af0c.png)

and if possible, also add an option to hide the mouseover glow from the button:
![image](https://user-images.githubusercontent.com/1942409/186416664-3aa05a0c-3ced-4256-808e-9fbed0a7f093.png)

^^ This can be done by

texture = button_name_here:GetHighlightTexture()
texture:SetAlpha(0)

Thx

**Comment by kapresoft** [comment]
Hi There,  
Thanks for the feedback.  I will add this option as soon as possible and hopefully on next release.  Thank you for using the addon.

**Comment by nfet** [comment]
Splitting this enhancement work into two. The mouseover glow will now be tracked in #41

**Comment by kapresoft** [comment]
Fixed in [1.0.0.29](https://www.curseforge.com/wow/addons/actionbarplus/files/3982207).
