### ISSUE TITLE
Losing position and cooldowns dont work

### ISSUE THREAD

**Issue by garnerjustin** [kapresoft/wow-addon-actionbar-plus#305]
Hello, 

I first want to say how much I have enjoyed this add on!!!  It's the first UI add on that isn't super confusing and does what I need it to do!  Thanks again!

I have used Actionbarplus for about 6 months with 0 issues.  The last several weeks I have experienced a few things:

1) My layout never saves when I logout or switch characters now.  I have checked the box to use individual profiles to no avail.
2) When I put things onto the bars the cooldowns do not show and they used to
3) If I put something that has a quantity (potion or explosive) it will randomly show the number of that item that I have in my bags for all bars in that array.  
4) It no longer "lights up" when in range of something like it used to and never shows a cooldown.
5) Sometimes when I put an ability into a slot and then place another ability in a different slot on the same bar it will overwrite the first ability with the second, even though I didn't play it there.

I am really hoping you can help me here, since I DO NOT want to give up using this add on!!!  

I have tried uninstalling (and removing the folder altogether) and reinstalling to no avail.  

Please help!!!

**Comment by nfet** [comment]
Hi There, What version of wow are you experiencing this? I may revert the recent changes completely.

**Comment by nfet** [comment]
Hi There, 
My sincere apologies for the bad user experience. What version of wow are you experiencing this? I may revert the recent changes completely.

**Comment by garnerjustin** [comment]
Thanks for reaching out!  I’m playing classic era 1.14.3 and add on version 2023.6.8. Thanks in advance for your help!Sent from my iPhoneOn Jun 26, 2023, at 6:16 PM, Tony Lagnada ***@***.***> wrote:﻿
Hi There,
My sincere apologies for the bad user experience. What version of wow are you experiencing this? I may revert the recent changes completely.

**Comment by garnerjustin** [comment]
Should I try an earlier version?  Or do I have a file that’s corrupted that lives outside of the normal add on folder (which I have deleted and re added several times)? Thank you!Sent from my iPhoneOn Jun 26, 2023, at 6:16 PM, Tony Lagnada ***@***.***> wrote:﻿
Hi There,
My sincere apologies for the bad user experience. What version of wow are you experiencing this? I may revert the recent changes completely.

**Comment by nfet** [comment]
I've had to turn off certain features recently to deal with some performance issues. If you can, please give me about a week to get things stable as I fix the issues forward.  I need to investigate all the issues you stated and make sure the functionalities are restored.

Again, I apologize and I am working as fast as I can to get this addon working properly for all versions of WoW.

**Comment by nfet** [comment]
Hi Again,

I couldn't repo 1 below. Can you create a new profile under Actionbar  Settings/profiles and see if this still occurs for you

> 1, My layout never saves when I logout or switch characters now. I have checked the box to use individual profiles to no avail.

![image](https://github.com/kapresoft/wow-addon-actionbar-plus/assets/1599306/84839ae1-f85a-40b2-8db1-62c71ee2411c)

For 4 below, I've had to turn this off for perf reasons, please give me some time to that feature back in. I find this very important as well.

> 4.  It no longer "lights up" when in range of something like it used to and never shows a cooldown.

For items 2, 3 and 5.  There was a Lua Error I discovered filed as Issue #306.  Can you see if release 2023.6.9 resolves this?

Please let me know which ones are not fixed with a repro.  

Cheers,
Tony

**Comment by garnerjustin** [comment]
Thank you for replying to me and offering assistance!  I’m so excited to try this when I get home and get my favorite add on working again!On Jun 26, 2023, at 11:56 PM, Tony Lagnada ***@***.***> wrote:﻿
Hi Again,
I couldn't repo 1 below. Can you create a new profile under Actionbar  Settings/profiles and see if this still occurs for you

1, My layout never saves when I logout or switch characters now. I have checked the box to use individual profiles to no avail.


For 4 below, I've had to turn this off for perf reasons, please give me some time to that feature back in. I find this very important as well.


It no longer "lights up" when in range of something like it used to and never shows a cooldown.


For items 2, 3 and 5.  There was a Lua Error I discovered filed as Issue #306.  Can you see if release 2023.6.9 resolves this?
Please let me know which ones are not fixed with a repro.
Cheers,
Tony

**Comment by nfet** [comment]
Hi @garnerjustin,
I reverted to version 2023.5.6 (now labeled as 2023.6.10).  Please get this version for stability.
- https://www.curseforge.com/wow/addons/actionbarplus/files/4612699

I want to apologize for the recent performance issues with the ActionbarPlus add-on. I've listened to your feedback and have taken quick action to address the problem. I've reverted the add-on to the previous version, now labeled as 2023.6.10 (originally 2023.5.6), which should resolve the issues.

I'm really sorry for any inconvenience caused. As a developer, I'm constantly learning and improving, but sometimes I make mistakes. Your support and feedback are incredibly important to me, and I'm grateful for your understanding.

If you're still experiencing any problems, please let me know. I'm committed to fixing any remaining issues and providing a better user experience.

Thank you for using ActionbarPlus and for your ongoing support.

Tony L.

**Comment by garnerjustin** [comment]
Thanks for your help!  I tossed you a $20 PayPal donation for all of your hard work. On Jun 27, 2023, at 5:24 PM, Tony Lagnada ***@***.***> wrote:﻿
Hi @garnerjustin,
I reverted to version 2023.5.6 (now labeled as 2023.6.10).  Please get this version for stability.

https://www.curseforge.com/wow/addons/actionbarplus/files/4612699

I want to apologize for the recent performance issues with the ActionbarPlus add-on. I've listened to your feedback and have taken quick action to address the problem. I've reverted the add-on to the previous version, now labeled as 2023.6.10 (originally 2023.5.6), which should resolve the issues.
I'm really sorry for any inconvenience caused. As a developer, I'm constantly learning and improving, but sometimes I make mistakes. Your support and feedback are incredibly important to me, and I'm grateful for your understanding.
If you're still experiencing any problems, please let me know. I'm committed to fixing any remaining issues and providing a better user experience.
Thank you for using ActionbarPlus and for your ongoing support.
Tony L.

**Comment by nfet** [comment]
Oh wow. I did not expect this. I just totally do this work for the love of the game and coding.  Thank you so much.

BTW,  I am working on (**Range Indicator no longer working** #310) and just got it working again. I am testing it across all 3 version to make sure there are no side effects.  I will tag you on the issue once I release it.

Please don't hesitate to file an issue for any bugs or feature request.

cheers again and many thanks
Tony L

**Comment by nfet** [comment]
The range indicator should be available shortly (r2023.7.1).  Any issues, please let me know.
- [r2023.7.1 in Curseforge](https://legacy.curseforge.com/wow/addons/actionbarplus/files/4627229)
