### ISSUE TITLE
Unable to move or remove items once placed. 

### ISSUE THREAD

**Issue by Mrfunreal** [kapresoft/wow-addon-actionbar-plus#344]
**Describe the bug**
Not sure if this is a bug, but I am not able to move or remove any item from the action bars once I placed them. I can replace items by placing them on top, but I can not for the life of me figure out how I can remove or move items.

**To Reproduce**
1. Try to move anything. At all.

**Expected behavior**
I was assuming I could just hold down and move an item like on the default bars. Even holding various modifier keys and right mouse click don't help.

**Operating System**
- OS: Win-10
- 
**Additional context**
Here's a screenshot of what addons I have installed, in case any of them would interfere.
![image](https://github.com/kapresoft/wow-addon-actionbar-plus/assets/62206882/144866d9-f73c-4f81-b8e0-1f897b4639ac)

**Comment by nfet** [comment]
Thanks for creating this. I believe there were some new changes in the new Gane Options menu that broke this. For some reason I did not see this issue locally and was not aware of it.

I'm verifying the fix now across all warcraft versions. I should have the fix released today.

Cheers,
Tony

**Comment by kapresoft** [comment]
![image](https://github.com/kapresoft/wow-addon-actionbar-plus/assets/42391379/56bb5c53-3ad4-4299-8966-5c0d0d61447d)

Fix is in [2024.1.4 Release](https://github.com/kapresoft/wow-addon-actionbar-plus/releases/tag/2024.1.4).
Should be available in [CurseForge](https://legacy.curseforge.com/wow/addons/actionbarplus/files/5061361) shortly.

### Notes

> The ABP addon uses the Standard Blizz "Lock Action Bars" settings.

The correct behavior should be:

1. If "Lock Action Bars" is unchecked, the action buttons will trigger on key release.  The user should be able to move the actions around without any modifier (ctrl, shift, alt).
2. If "Lock Action Bars" is checked, the action buttons will trigger on key down. The user should be able to move the actions around with the selected modifier key (ctrl, shit, or alt).
3. If "Lock Action Bars" is checked and modifier key is 'NONE', same behavior as number 2 above, except the action buttons are locked and can't be moved around.
