### ISSUE TITLE
{{ActionbarPlus::ButtonFactory::BN}}: OnPlayerMount called...

### ISSUE THREAD

**Issue by DrowningB** [kapresoft/wow-addon-actionbar-plus#375]
**Describe the bug**
randomly and anytime you mount up no matter which actionbar you use(wows own bars or abp bars a message displays in the ingame chat without making any sense {{ActionbarPlus::ButtonFactory::BN}}: OnPlayerMount called...

**To Reproduce**
1. Just click on any mount icon on any actionbar
2. The message will popup in chat(sometimes spammed)

**Expected behavior**
No messages in ingame chat

**Screenshots**
![WoWScrnShot_032024_142149](https://github.com/kapresoft/wow-addon-actionbar-plus/assets/164190377/227bc8c9-fd0b-4a11-b2d4-0dba49579b0f)

**Operating System**
- OS: [e.g. Windows
- Version WOTLK classic

**Additional context**
Its just very frustrating to have the ingame chat spammed constantly with no way to turn it off

**Comment by nfet** [comment]
My apologies that this verbose log message went through. It was not my intention.  Please pickup the latest at 
https://legacy.curseforge.com/wow/addons/actionbarplus/files/5198293.

Thank you for using my addon.  Take care.

#### Release Notes:
https://github.com/kapresoft/wow-addon-actionbar-plus/releases/tag/2024.3.3

**Comment by DrowningB** [comment]
Hello,

Thank you for fixing this so fast!!
Love your addons and thanks!

-  Drowning


Verzonden vanuit Outlook<http://aka.ms/weboutlook>

________________________________
Van: Tony Lagnada ***@***.***>
Verzonden: woensdag 20 maart 2024 17:22
Aan: kapresoft/wow-addon-actionbar-plus ***@***.***>
CC: DrowningB ***@***.***>; Author ***@***.***>
Onderwerp: Re: [kapresoft/wow-addon-actionbar-plus] {{ActionbarPlus::ButtonFactory::BN}}: OnPlayerMount called... (Issue #375)


My apologies that this verbose log message went through. It was not my intention. Please pickup the latest at
https://legacy.curseforge.com/wow/addons/actionbarplus/files/5198293.

Thank you for using my addon. Take care.

Release Notes:

https://github.com/kapresoft/wow-addon-actionbar-plus/releases/tag/2024.3.3
