### ISSUE TITLE
Macro Spells with modifier key does not change icon texture

### ISSUE THREAD

**Issue by nfet** [kapresoft/wow-addon-actionbar-plus#40]
## Details
Given the following Macro, the icon should change when "SHIFT" or "ALT" keys are pressed.
In addition, the cooldown of the current spell should be show as well when pressing the modifier keys.

```
/cast [mod:shift] Blackout Kick
/cast [mod:alt] Roll
/cast [nomod] Tiger Palm
```

**Comment by kapresoft** [comment]
Fixed in [1.0.0.29](https://www.curseforge.com/wow/addons/actionbarplus/files/3982207) ~ but still have issues with receiving events unless the macro also exists in the standard blizzard actionbar.
