### ISSUE TITLE
Cannot add spells to actionbars

### ISSUE THREAD

**Issue by lorewalkercho** [kapresoft/wow-addon-actionbar-plus#422]
**Describe the bug**
I cannot place spells on ActionbarPlus bars. When I use LMB to drag and drop a spell to the AB+ bars, the slot I'm hovering over is highlighted like it sees me holding the spell there, but when I let go of LMB to drop the spell it just disappears. This happens whether I drag the spell from the spellbook or from a default actionbar. This ONLY happens with spells, I can drag and drop items from my bag and macros from /macro just fine.

**To Reproduce**
1. Enable an AB+ actionbar
2. Try to drag a spell from the spellbook to the AB+ bar
3. The spell just disappears

**Operating System**
- OS: Windows
- Version: Retail
- Addon Version: 2024.5.4

**Additional context**
I tried disabling all other addons and relaunched the game, it did not solve the issue.

**Comment by srliao** [comment]
Getting the same bug. This is Lua error captured by BugSack
```lua
1x ActionbarPlus/Core/Lib/API/API.lua:294: attempt to call global 'GetSpellInfo' (a nil value)
[string "@ActionbarPlus/Core/Lib/API/API.lua"]:294: in function `GetSpellInfo'
[string "@ActionbarPlus/Core/Lib/Widget/Buttons/SpellDragEventHandler.lua"]:44: in function `Handle'
[string "@ActionbarPlus/Core/Lib/Widget/Buttons/ReceiveDragEventHandler.lua"]:63: in function `Handle'
[string "@ActionbarPlus/Core/Lib/Widget/Buttons/ButtonUI.lua"]:148: in function <...s/ActionbarPlus/Core/Lib/Widget/Buttons/ButtonUI.lua:135>
[string "@ActionbarPlus/Core/Lib/Widget/Buttons/ButtonUI.lua"]:209: in function <...s/ActionbarPlus/Core/Lib/Widget/Buttons/ButtonUI.lua:205>
[string "=(tail call)"]: ?
[string "=[C]"]: ?

Locals:
self = <table> {
 ACTION_BUTTON_USE_KEY_DOWN = "ActionButtonUseKeyDown"
 mt = <table> {
 }
 LOCK_ACTION_BARS = "lockActionBars"
}
spellNameOrId = 29166
(*temporary) = nil
(*temporary) = 29166
(*temporary) = "attempt to call global 'GetSpellInfo' (a nil value)"
```
