### ISSUE TITLE
Should not have to reload when Updating button size in Options UI

### ISSUE THREAD

**Issue by nfet** [kapresoft/wow-addon-actionbar-plus#6]
### Details
1. Open Options UI with ```/abp``` console command
1. Change the button size (physical dimension)
    - Desired Result:  ActionbarPlus buttons will render without having to reload

**Comment by kapresoft** [comment]
Fixed in [1.0.0.20](https://www.curseforge.com/wow/addons/actionbarplus/files/3831286)
