### ISSUE TITLE
Add more row and columns

### ISSUE THREAD

**Issue by AaronHernandezPerez** [kapresoft/wow-addon-actionbar-plus#71]
It would be very useful to be able to have more rows and columns per bar, so we don't have to align several bars to have more slots

**Comment by nfet** [comment]
Hi Aaron,Max rows or cols is 10, which means you can have up to 10x10.  What would be desirable for a max? 20x20? Did you have anything in mind.

**Comment by AaronHernandezPerez** [comment]
As a matter of fact, i was already doing some tests, for example in my case i can use 17 columns to put it below the chat, if it isn't an issue could you make it a huge number so people have the choice? something like 40.

As a bonus I was experimenting making the background transparent like the default blizzard action bars

![image](https://user-images.githubusercontent.com/45629114/193097021-0462247a-5efb-464d-ad68-094064917e47.png)

**Comment by nfet** [comment]
40 sounds reasonable.  I'm gonna see how this addon performs with that many button.  I may put some weird rules on the limit that says, if cols is > 40 then only allow 2 rows, etc.  I will keep the first 50 buttons to be eligible for keybind unchanged for now...the  Bindings.xml is a bit static.

I'll track this on a new story/issue.  I was eventually going to get to the cosmetics part of it.
>As a bonus I was experimenting making the background transparent like the default blizzard action bars

Thanks for the feedback!

**Comment by nfet** [comment]
I just did a 10x40 and seems to peform fine.  I'll brute force it for now and send a 1.0.1.2 update.  This is awesome. Checkout the screen. ha ha.

<img width="2202" alt="Screen Shot 2022-09-29 at 1 40 55 PM" src="https://user-images.githubusercontent.com/1599306/193137892-e72b8ae7-1002-4afe-bfdc-32a4f5e1adbc.png">

**Comment by AaronHernandezPerez** [comment]
Great! thanks for the update

**Comment by nfet** [comment]
> 40 sounds reasonable. I'm gonna see how this addon performs with that many button. I may put some weird rules on the limit that says, if cols is > 40 then only allow 2 rows, etc. I will keep the first 50 buttons to be eligible for keybind unchanged for now...the Bindings.xml is a bit static.
> 
> I'll track this on a new story/issue. I was eventually going to get to the cosmetics part of it.
> 
> > As a bonus I was experimenting making the background transparent like the default blizzard action bars
> 
> Thanks for the feedback!

FYI, Here's the new story for tracking:
- Provide options to make background transparent #72

**Comment by nfet** [comment]
In release 1.0.2
- https://www.curseforge.com/wow/addons/actionbarplus/files/4012066
- https://github.com/kapresoft/wow-addon-actionbar-plus/releases/tag/1.0.2

**Comment by tflo** [comment]
I stumbled upon the same issue but with rows, where the max is still 10 (version 1.0?[^1]).

Here for example I tried to reduplicate one of my ButtonForge bars (12 rows), but it was not possible due to that limitation:

![WoWScrnShot_100622_134958](https://user-images.githubusercontent.com/1410282/194307663-a0905941-ef4c-4542-8bb5-444c84b99f99.png)

12 rows do not seem excessive to me ;)

I changed the rows.max to 20 in your config.lua, and nothing bad happened, buttons seem to work fine.

Please consider increasing the max rows, unless there are some technical obstacles.

Thanks,

– Tom

[^1]: The toc file says version _1.0_, the zip archive is named as version _1.0.3.7._
