### ISSUE TITLE
Provide options to hide buttons that are empty

### ISSUE THREAD

**Issue by nfet** [kapresoft/wow-addon-actionbar-plus#72]
New story pulled from #71 - Add more row and columns
>As a bonus I was experimenting making the background transparent like the default blizzard action bars

## Details
- Initially, have an option to make background transparent like the default blizz behavior
- In a future story, add more background options (see ElvUI options to get some insparations :-)).

@AaronHernandezPerez, FYI

**Comment by nfet** [comment]
Create a similar Blizzard Interface/Actionbar option, default as "checked"

![image](https://user-images.githubusercontent.com/1599306/193360299-1dc0620c-7568-4a75-b70f-b8201e6d254b.png)

**Comment by nfet** [comment]
@AaronHernandezPerez, Just a minor update. I've got a rough implementation of transparent backgrounds. I just need to spend some time finalizing it with a settings. FYI. I'm fairly excited to get this feature published.

https://user-images.githubusercontent.com/1599306/193431293-3cedbfd0-dc09-4763-a7e9-6a81932b8ff4.mov

**Comment by AaronHernandezPerez** [comment]
Oh that looks amazing!, Just some feedback make sure you can see the bar or something if we don't have any spells added to it, or people are going to wonder where it is :P

**Comment by nfet** [comment]
That's a good point 😄 .  Might have to think of something.  I hate the idea of having to something like `/abp move` like elvui to toggle anchors. but we'll see.
