### ISSUE TITLE
[suggestion] Increase max rows

### ISSUE THREAD

**Issue by tflo** [kapresoft/wow-addon-actionbar-plus#86]
Similar to https://github.com/kapresoft/wow-addon-actionbar-plus/issues/71:

I stumbled upon the same issue but with rows, where the max is still 10 (version 1.0?[^1]).

Here for example I tried to reduplicate one of my ButtonForge bars (12 rows), but it was not possible due to that limitation:

![WoWScrnShot_100622_134958](https://user-images.githubusercontent.com/1410282/194307663-a0905941-ef4c-4542-8bb5-444c84b99f99.png)

12 rows do not seem excessive to me ;)

I changed the rows.max to 20 in your config.lua, and nothing bad happened, buttons seem to work fine.

Please consider increasing the max rows, unless there are some technical obstacles.

Thanks,

– Tom

[^1]: The toc file says version _1.0_, the zip archive is named as version _1.0.3.7._

**Comment by nfet** [comment]
Thanks Tom.  Will make that update.  I don't believe there is a concern technically, except, the keybinding portion of blizz is a bit static to change.  I've limited the number to first 50 buttons currently.  I can make a 20 max rows for start.  If someone reports a performance issue, I'll put some smarts in the config to limit the amount of buttons based on the cols x rows selection.
>Please consider increasing the max rows, unless there are some technical obstacles.

**Comment by nfet** [comment]
v1.0.3.8 Should be avaiable on Curseforge shortly -- https://www.curseforge.com/wow/addons/actionbarplus/files
