### ISSUE TITLE
Option to hide bars in pet battle and vehicle

### ISSUE THREAD

**Issue by tflo** [kapresoft/wow-addon-actionbar-plus#87]
Unless I'm blind, I think there should be an option to hide the bars during pet battles.

I'm not sure if this should be a global option or a bar specific option. Right now I don't see the need to have any of my bars in pet pattles, so – personally –  I _tend_ to think a global option (set to 'hide' by default) would be sufficient.

I haven't checked how the bars behave while in a vehicle, or in general when we have a vehicle actionbar or an actionbar override. Probably they should be hidden there too, or have an option for that.

– Tom

**Comment by nfet** [comment]
Hi, if you agree, I just double checked the pet battle (and I probably can say the same about vehicles) that there is definitely no use for the action bars on pet battle or vehicle events.  So, I would probably say hide the bars in this situation and probably no need to make it an option.  I could probably say the same about the "during flight" mode, but that option is already there :-).

**Comment by nfet** [comment]
I just want to note before I forgot that I didn't provide and option during pet battles.  I created a separate story for vehicle #96 and modified the title of this story and removed "and vehicle".  I didn't have time to implement the vehicle part this week so I will bump to Milestone 10.3.
